apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubes-counter-api
  labels:
    app: kubes-counter-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubes-counter-api
  template:
    metadata:
      labels:
        app: kubes-counter-api
    spec:
      containers:
        - name: counter-api
          image: craigderington/kubes-counter-api:latest
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: kubes-counter-api
spec:
  type: LoadBalancer
  selector:
    app: kubes-counter-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubes-counter-web
  labels:
    app: kubes-counter-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubes-counter-web
  template:
    metadata:
      labels:
        app: kubes-counter-web
    spec:
      containers:
        - name: kubes-counter-web
          image: craigderington/kubes-counter-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: counter-web
spec:
  type: LoadBalancer
  selector:
    app: kubes-counter-web
  ports:
    - name: http
      port: 8080
      targetPort: 8080

